// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OnlineCrimeRepo.Models;
using System;

namespace OnlineCrimeRepo.Migrations
{
    [DbContext(typeof(OrpContext))]
    [Migration("20180510212625_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("OnlineCrimeRepo.Models.Criminal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Complexion");

                    b.Property<int>("CrimeRate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EyeColor");

                    b.Property<string>("Gender");

                    b.Property<string>("Height");

                    b.Property<string>("Name");

                    b.Property<string>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
